Added list functions as required
deploifai/cli pull request #36
Opened 2022-07-18 08:07 UTC by ExtinctWolf83

2022-07-18 17:32 UTC, 98sean98 reviewed
Still missing some necessary changes using the `whereProject` argument queries for data storages querying in the `dataset list` command

2022-07-18 17:32 UTC, 98sean98 commented on deploifai/cloud_profile/list.py
> +    Command to list all cloud profiles linked to the current workspace
I think we can shorten the text a bit more with just `List all cloud profiles in the current workspace`

2022-07-18 17:32 UTC, 98sean98 commented on deploifai/data/list.py
> +def list_data(context: DeploifaiContextObj):
As discussed, listing priority should be
1. command option for project name
2. project id in local config (if found)
3. current workspace in global config (if project not found in local config)

2022-07-20 09:18 UTC, 98sean98 requested changes
Just some small changes.

2022-07-20 10:38 UTC, ExtinctWolf83 commented on deploifai/server/list.py
> +        variables = {"project": {"is": {"name": {"equals": project}}}}
refactored

2022-07-20 10:38 UTC, ExtinctWolf83 commented on deploifai/api/__init__.py
> +    def get_data_storages(self, workspace: str, where_data_storage: str = None):
refactored

2022-07-20 10:38 UTC, ExtinctWolf83 commented on deploifai/api/__init__.py
> +    def get_training_server(self, workspace: str, where_training_server: str = None):
refactored

2022-07-20 10:38 UTC, ExtinctWolf83 commented on deploifai/server/list.py
> +                            }
yes
removed

2022-07-20 11:34 UTC, 98sean98 approved these changes

2022-07-21 03:07 UTC, merged