60 local cloud profile credentials
deploifai/cli pull request #61
Opened 2023-02-21 17:23 UTC by yawjalik

- Cloud profile create now supports `-p` or `--provider` flag to specify the provider without going through a prompt
- boto3 is used to get local AWS credentials (from .aws)
- These credentials are used to create an IAM user with a username specified by the provided cloud profile name
- After attaching policies to the user, another set of credentials are generated to create the cloud profile on deploifai
- If no AWS local credentials can be found, the user will be prompted to enter the credentials manually

** messages and error handling can be further cleaned up

2023-02-22 06:26 UTC, 98sean98 commented
Could you also help check whether `PowerUser` and `IAMFullAccess` are enough? try creating a cloud profile with these only, and use it to create all the different resources we offer. You can just do it against the production platform.

2023-02-23 07:17 UTC, yawjalik commented
May consider to include a flag `--profile` to specify profile without going through the prompt.

2023-02-23 14:19 UTC, 98sean98 requested changes
Pretty good work. Just that error message should be a bit more informative, that's all.

2023-02-23 14:19 UTC, 98sean98 commented on deploifai/cloud_profile/create.py
> +            click.secho('No AWS credentials found. Please set this up', fg="red")
`AWS credentials not found. Please set it up with "aws configure", or go to https://docs.deploif.ai/cloud-services/connect-your-account/aws to learn how to create AWS credentials for Deploifai on the dashboard.`

2023-02-23 15:59 UTC, merged