Create Azure cloud profile via CLI
deploifai/cli pull request #79
Opened 2023-03-28 09:06 UTC by yawjalik

2023-04-03 07:04 UTC, utkarsh867 commented
@yawjalik @98sean98 What is this waiting on?

2023-04-03 09:11 UTC, 98sean98 requested changes
Let the user choose which az account they want to use deploifai for.

2023-04-03 09:11 UTC, 98sean98 commented on deploifai/cli/cloud_profile/create.py
> +        # Get subscription ID
Should prompt the user which `az account` to use by querying `az account list` and setting it with `az account set --subscription [subscription_id]`

2023-04-11 19:11 UTC, 98sean98 approved these changes

2023-04-11 19:11 UTC, merged